name: Publish Black Night 🌃 distributions 📦 to PyPI

on:
    push:
        branches:
            - main
        paths:
            - 'black_night/__init__.py'

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v1
          with:
            python-version: '3.10'
        - name: Install pypa/build
          run: >-
            python -m
            pip install
            build
            --user
        - name: Build a binary wheel and a source tarball
          run: >-
            python -m
            build
            --sdist
            --wheel
            --outdir dist/
            .
        - name: Publish distribution 📦 to PyPI
          uses: pypa/gh-action-pypi-publish@v1.5.0
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
